on: pull_request

jobs:
  build_and_deploy_tests:
    runs-on: ubuntu-latest
    name: Build and Deploy Wrangler Action Tests
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "latest"
          cache: "npm"

      - name: Install Dependencies
        run: npm install

      - name: Build Action
        run: npm run build

      - name: Only Build App
        uses: ./
        with:
          workingDirectory: "./test"
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          postCommands: npx wrangler deploy --dry-run && exit 0

      - name: Deploy app w/ apiToken
        uses: ./
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          workingDirectory: "./test"

      - name: Deploy app w/ hardcoded Wrangler v2
        uses: ./
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          wranglerVersion: "2.20.0"
          workingDirectory: "./test"

      - name: Deploy app w/ secrets
        uses: ./
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          workingDirectory: "./test"
          secrets: |
            SECRET1
            SECRET2
          preCommands: |
            echo "*** pre commands ***"
            echo "******"
          postCommands: |
            echo "*** post commands ***"
            echo "******"
        env:
          SECRET1: ${{ secrets.SECRET1 }}
          SECRET2: ${{ secrets.SECRET2 }}
